dataset_params:
  name: MEAD
  root_dir: dataset/MEAD/
  frame_shape: [256, 256, 3]
  id_sampling: False
  augmentation_params:
    crop_mouth_param: 
      center_x: 135
      center_y: 190
      mask_width: 100
      mask_height: 60
    rotation_param: 
      degrees: 30
    perspective_param: 
      pers_num: 30
      enlarge_num: 40
    flip_param:
      horizontal_flip: True
      time_flip: False
    jitter_param: 
      brightness: 0
      contrast: 0
      saturation: 0
      hue: 0

model_params:
  common_params:
    num_kp: 10
    num_channels: 3
    estimate_jacobian: True
  audio_params:
    num_kp: 10
    num_channels : 3
    num_channels_a : 3
    estimate_jacobian: True
  kp_detector_params:
     temperature: 0.1
     block_expansion: 32
     max_features: 1024
     scale_factor: 0.25
     num_blocks: 5
  generator_params:
    block_expansion: 64
    max_features: 512
    num_down_blocks: 2
    num_bottleneck_blocks: 6
    estimate_occlusion_map: True
    dense_motion_params:
      block_expansion: 64
      max_features: 1024
      num_blocks: 5
      scale_factor: 0.25
  discriminator_params:
    scales: [1]
    block_expansion: 32
    max_features: 512
    num_blocks: 4
    sn: True

train_params:
  type: linear_4
  smooth: False
  jaco_net: cnn
  ldmark: fake
  generator: not
  num_epochs: 300
  num_repeats: 1
  epoch_milestones: [60, 90]
  lr_generator: 2.0e-4
  lr_discriminator: 2.0e-4
  lr_kp_detector: 2.0e-4
  lr_audio_feature: 2.0e-4
  batch_size: 16
  scales: [1, 0.5, 0.25, 0.125]
  checkpoint_freq: 1
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    generator_gan: 0
    discriminator_gan: 0
    feature_matching: [10, 10, 10, 10]
    perceptual: [10, 10, 10, 10, 10]
    equivariance_value: 0
    equivariance_jacobian: 0
    emo: 10


visualizer_params:
  kp_size: 5
  draw_border: True
  colormap: 'gist_rainbow'
